export const TYPES = {
  ADD_FOLDER: "ADD_FOLDER",
  DELETE_FOLDER: "DELETE_FOLDER",
  ADD_CATEGORY: "ADD_CATEGORY",
  DELETE_CATEGORY: "DELETE_CATEGORY",
  EDIT_CATEGORY: "EDIT_CATEGORY",
  ADD_PRODUCT: "ADD_PRODUCT",
  DELETE_PRODUCT: "DELETE_PRODUCT",
  EDIT_PRODUCT: "EDIT_PRODUCT",
  EDIT_NOTE: "EDIT_NOTE",
};
